name: Lint Python Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Нужно для git push

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Check if this is a fork
      id: fork-check
      run: |
        echo "IS_FORK=false" >> "$GITHUB_ENV"
        if [ "${{ github.repository }}" != "YuriSilenok/gibdd_bot_44" ]; then
          echo "IS_FORK=true" >> "$GITHUB_ENV"
        fi

    - name: Commit and push changes (only if not a fork)
      if: env.IS_FORK == 'false'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Install dependencies
      if: env.IS_FORK == 'false'
      run: pip install black ruff

    - name: Format code with black
      if: env.IS_FORK == 'false'
      run: black .

    - name: Commit and push changes by black
      if: env.IS_FORK == 'false'
      run: |
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "chore: auto-fix formatting via GitHub Actions by black"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Format code with ruff
      if: env.IS_FORK == 'false'
      run: ruff check . --fix --unsafe-fixes || true

    - name: Commit and push changes by ruff
      if: env.IS_FORK == 'false'
      run: |
        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "chore: auto-fix formatting via GitHub Actions by ruff"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi


    - name: Install dependencies
      run: pip install flake8 astroid==2.12.13 pylint pylint-peewee
  
    - name: Run flake8
      run: flake8 .

    - name: Run pylint
      run: pylint $(find . -name "*.py" ! -path "./venv/*")
